#!/usr/bin/env node

/*
  Produces icons.ts for you, which imports each requested icon, and adds the
  imported SvgComponent to a map that can be used by the base/Icon.astro component.

  This will automatically grab every SVG in the src/assets/icons directory, and
  add them under the 'local' tag, in addition to the explicit list of external
  package icons.

  If you need to add additional icons from an external package, put them in the
  "icons" list below, then run this script to regenerate src/icons.ts.
*/

// These paths are both interpreted relative to the root project directory
// (where icons-generator.ts must be located).
const localDir = '/src/assets/icons';
const genfile = '/src/components/base/assets/icons.ts';

const libMap = new Map([
  ['local', localDir],

  // ** Tabler **
  // Install with 'npm install tabler/icons', then uncomment line below:
  ['tabler', '/node_modules/@tabler/icons/icons/outline'],
  ['tabler-filled', '/node_modules/@tabler/icons/icons/filled'],

  // ** Lucide **
  // Install with 'npm install lucide-static', then uncomment line below:
  //['lucide', '/node_modules/lucide-static/icons'],

  // ** Simple **
  // Install with 'npm install simple-icons', then uncomment line below:
  //['simple', '/node_modules/simple-icons/icons'],

  // ** Material Symbols (Google) **
  // Install with 'npm install @material-symbols/svg-400@latest', then uncomment line below:
  //['material', '/node_modules/@material-symbols/svg-400/outlined'],
]);

const icons = [
  ['tabler', 'chevrons-down'],
  ['tabler', 'x'],
  ['tabler', 'heart-handshake'],
  ['tabler', 'mail-plus'],
  ['tabler', 'phone'],
  ['tabler', 'mail'],
  ['tabler', 'map-pin'],
  ['tabler', 'clock'],
  ['tabler', 'quote'],
  ['tabler', 'rocket'],
  ['tabler', 'sun'],
  ['tabler', 'moon'],
  ['tabler', 'menu-2'],
  ['tabler', 'external-link'],
  ['tabler', 'alert-triangle'],
  ['tabler', 'circle-check'],
];


// ---------------------------------------------

import { fileURLToPath } from 'url';
import { dirname, basename, join, parse } from 'path';
import { createWriteStream, globSync } from 'node:fs';

const scriptPath = fileURLToPath(import.meta.url);
const scriptFile = basename(scriptPath);
const baseDir = dirname(scriptPath);
const filePath = join(baseDir, genfile);
const file = createWriteStream(filePath);

// Glob all SVG files in the local icons directory, and add them to the icons list.
for (const path of globSync( join(baseDir, localDir, '*.svg') )) {
  const { name } = parse(path);
  icons.push(['local', name]);
}

// Write file header.
file.write(
  '// *** THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ***\n' +
  `// Generated by ${scriptFile} at ${new Date().toISOString()}\n` +
  '//\n' +
  '// This file is used as a source of icons for the base/Icon.astro component.\n' +
  `// (to add more icons, edit the 'icons' array at the top of ${scriptFile})\n\n`
);

// Write static imports for each individual icon.
for (const [index, [lib, name]] of icons.entries()) {
  const libPath = libMap.get(lib);
  if (!libPath) {
    throw new Error(`Library for icon #${index} (${lib}, ${name}) is invalid, skipping.`);
  }
  file.write(`import Icon${index} from "${join(libPath, name+".svg")}"\n`);
}

// Write a map from icon tag (lib:name) to the imported SVG component.
file.write("\nexport const iconMap = new Map([\n");
for (const [index, [lib, name]] of icons.entries()) {
  file.write(`  ["${lib+":"+name}", Icon${index}],\n`);
}
file.write("]);");

file.end();

console.log("Successfully wrote to " + filePath);