// *** THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ***
// Generated by icons-generator.ts at 2026-03-22T05:08:25.777Z
//
// This file is used as a source of icons for the base/Icon.astro component.
// (to add more icons, edit the 'icons' array at the top of icons-generator.ts)

import Icon0 from "/node_modules/@tabler/icons/icons/outline/chevrons-down.svg"
import Icon1 from "/node_modules/@tabler/icons/icons/outline/x.svg"
import Icon2 from "/node_modules/@tabler/icons/icons/outline/heart-handshake.svg"
import Icon3 from "/node_modules/@tabler/icons/icons/outline/mail-plus.svg"
import Icon4 from "/node_modules/@tabler/icons/icons/outline/phone.svg"
import Icon5 from "/node_modules/@tabler/icons/icons/outline/mail.svg"
import Icon6 from "/node_modules/@tabler/icons/icons/outline/map-pin.svg"
import Icon7 from "/node_modules/@tabler/icons/icons/outline/clock.svg"
import Icon8 from "/node_modules/@tabler/icons/icons/outline/quote.svg"
import Icon9 from "/node_modules/@tabler/icons/icons/outline/rocket.svg"
import Icon10 from "/node_modules/@tabler/icons/icons/outline/sun.svg"
import Icon11 from "/node_modules/@tabler/icons/icons/outline/moon.svg"
import Icon12 from "/node_modules/@tabler/icons/icons/outline/menu-2.svg"
import Icon13 from "/node_modules/@tabler/icons/icons/outline/external-link.svg"
import Icon14 from "/node_modules/@tabler/icons/icons/outline/alert-triangle.svg"
import Icon15 from "/src/assets/icons/ccc-logo-wide.svg"
import Icon16 from "/src/assets/icons/ccc-logo.svg"
import Icon17 from "/src/assets/icons/donate.svg"
import Icon18 from "/src/assets/icons/facebook.svg"
import Icon19 from "/src/assets/icons/instagram.svg"

export const iconMap = new Map([
  ["tabler:chevrons-down", Icon0],
  ["tabler:x", Icon1],
  ["tabler:heart-handshake", Icon2],
  ["tabler:mail-plus", Icon3],
  ["tabler:phone", Icon4],
  ["tabler:mail", Icon5],
  ["tabler:map-pin", Icon6],
  ["tabler:clock", Icon7],
  ["tabler:quote", Icon8],
  ["tabler:rocket", Icon9],
  ["tabler:sun", Icon10],
  ["tabler:moon", Icon11],
  ["tabler:menu-2", Icon12],
  ["tabler:external-link", Icon13],
  ["tabler:alert-triangle", Icon14],
  ["local:ccc-logo-wide", Icon15],
  ["local:ccc-logo", Icon16],
  ["local:donate", Icon17],
  ["local:facebook", Icon18],
  ["local:instagram", Icon19],
]);