// *** THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ***
// Generated by icons-generator.ts at 2026-03-15T22:48:17.310Z
//
// This file is used as a source of icons for the src/components/base/Icon.astro component.
// (to add more icons, edit the 'icons' array at the top of icons-generator.ts)

import Icon0 from "@node_modules/@tabler/icons/icons/outline/file-unknown.svg"
import Icon1 from "@node_modules/@tabler/icons/icons/outline/chevrons-down.svg"
import Icon2 from "@node_modules/@tabler/icons/icons/outline/x.svg"
import Icon3 from "@node_modules/@tabler/icons/icons/outline/heart-handshake.svg"
import Icon4 from "@node_modules/@tabler/icons/icons/outline/mail-plus.svg"
import Icon5 from "@node_modules/@tabler/icons/icons/outline/phone.svg"
import Icon6 from "@node_modules/@tabler/icons/icons/outline/mail.svg"
import Icon7 from "@node_modules/@tabler/icons/icons/outline/map-pin.svg"
import Icon8 from "@node_modules/@tabler/icons/icons/outline/clock.svg"
import Icon9 from "@node_modules/@tabler/icons/icons/outline/quote.svg"
import Icon10 from "@node_modules/@tabler/icons/icons/outline/rocket.svg"
import Icon11 from "@node_modules/@tabler/icons/icons/outline/sun.svg"
import Icon12 from "@node_modules/@tabler/icons/icons/outline/moon.svg"
import Icon13 from "@node_modules/@tabler/icons/icons/outline/menu-2.svg"
import Icon14 from "@node_modules/@tabler/icons/icons/outline/external-link.svg"
import Icon15 from "@/assets/icons/ccc-logo-wide.svg"
import Icon16 from "@/assets/icons/facebook.svg"
import Icon17 from "@/assets/icons/instagram.svg"

export const iconMap = new Map([
  ["tabler:file-unknown", Icon0],
  ["tabler:chevrons-down", Icon1],
  ["tabler:x", Icon2],
  ["tabler:heart-handshake", Icon3],
  ["tabler:mail-plus", Icon4],
  ["tabler:phone", Icon5],
  ["tabler:mail", Icon6],
  ["tabler:map-pin", Icon7],
  ["tabler:clock", Icon8],
  ["tabler:quote", Icon9],
  ["tabler:rocket", Icon10],
  ["tabler:sun", Icon11],
  ["tabler:moon", Icon12],
  ["tabler:menu-2", Icon13],
  ["tabler:external-link", Icon14],
  ["local:ccc-logo-wide", Icon15],
  ["local:facebook", Icon16],
  ["local:instagram", Icon17],
]);