name: rebase-prod

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
        default: 'main'

permissions:
  contents: write

jobs:
  rebase:
    runs-on: [ ubuntu-latest ]

    concurrency:
      group: "rebase-${{ github.ref_name }}-on-${{ inputs.branch }}"
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Rebase ${{ github.ref_name }} on ${{ inputs.branch }}
        uses: martincostello/rebaser@v3
        id: rebase
        with:
          branch: ${{ inputs.branch }}

      - name: Push changes
        if : ${{ steps.rebase.outputs.result == 'success' }}
        run: git push origin ${{ github.ref_name }} --force-with-lease
